# Generated by Django 5.0.1 on 2024-01-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_at', models.DateTimeField(auto_now=True)),
                ('tax_amount', models.CharField(max_length=5)),
                ('total_amount', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_email', models.EmailField(max_length=30, unique=True)),
                ('u_password', models.CharField(max_length=20)),
                ('u_contact', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Truckpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('t_email', models.EmailField(max_length=30, unique=True)),
                ('t_password', models.CharField(max_length=20)),
                ('t_contact', models.CharField(max_length=11)),
                ('t_address', models.CharField(max_length=50)),
                ('t_aadharcard_details', models.CharField(max_length=30, unique=True)),
                ('t_pancard_details', models.CharField(max_length=30, unique=True)),
                ('t_drivinglicence_details', models.CharField(max_length=30, unique=True)),
                ('t_bank_details', models.CharField(max_length=30, unique=True)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('f_type', models.CharField(max_length=30)),
                ('f_packages', models.CharField(max_length=20)),
                ('f_registration_no', models.CharField(max_length=11)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.truckpartner')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
